name: CI for PHP App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  php-tests:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリのチェックアウト
        uses: actions/checkout@v3

      - name: PHPのセットアップ
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          coverage: xdebug

      - name: Composer依存パッケージインストール
        run: composer install --prefer-dist --no-progress

      - name: PHPUnit実行
        run: vendor/bin/phpunit --coverage-text --colors=never